name: build

on:
  push:
    branches: [ "main" ]
    paths:
      - '**/*.cs'
  pull_request:
    paths:
      - '**/*.cs'
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    uses: KSPModdingLibs/KSPBuildTools/.github/workflows/build.yml@main
    with:
      solution-file-path: 'Source/KSPCommunityPartModules.sln'
      use-ckan: true
